spring.application.name=Webapp


# Removing the banner for the spring
spring.main.banner-mode=off

# Database Connection for the web
spring.datasource.url=jdbc:mysql://localhost:3306/proj_servetech_db
spring.datasource.username=proj-crtr
spring.datasource.password=projservetech

# Default username and password for the web security
spring.security.user.name=user
spring.security.user.password=user

# For autocreating tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
app.jwt.secret=mySecretKeyForJWTTokenGenerationAndValidation12345678
app.jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.ServeTech.Webapp=DEBUG