spring.application.name=Webapp


# Removing the banner for the spring
spring.main.banner-mode=off

# Database Connection for the web
spring.datasource.url=jdbc:mysql://localhost:3306/proj_servetech_db
spring.datasource.username=proj-crtr
spring.datasource.password=projservetech

# Default username and password for the web security
spring.security.user.name=user
spring.security.user.password=user